---
deployment:
  tasks:
    - export DEPLOYPATH=/home/astermac/public_html/
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R .next $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - cd $DEPLOYPATH && npm install --omit=dev
    - cd $DEPLOYPATH && npm run build