---
deployment:
  tasks:
    - export DEPLOYPATH=/home/astermac/public_html/
    - rm -rf $DEPLOYPATH/*
    - cp -R /home/astermac/repositories/entelverse/.next $DEPLOYPATH
    - cp /home/astermac/repositories/entelverse/package.json $DEPLOYPATH
    - cd $DEPLOYPATH && npm install --omit=dev
    - cd $DEPLOYPATH && npm run build